import { existsSync } from "fs";
import { chmod, mkdir, writeFile } from "fs/promises";
import { join, resolve } from "path";
import { getReplayPath } from "@replay-cli/shared/getReplayPath";
import { exitProcess } from "@replay-cli/shared/process/exitProcess";
import { registerCommand } from "../utils/commander/registerCommand";
import { getBrowserPath } from "../utils/browser/getBrowserPath";

const SUPPORTED_VERSIONS = ["131"];

registerCommand("get-adapter-browser", {
  checkForNpmUpdate: false,
  checkForRuntimeUpdate: false,
  requireAuthentication: false,
})
  .description(
    "Get path to an adapter script that makes replay-chrome work as a drop-in replacement for a newer Chrome version"
  )
  .argument("<chrome-version>", "Target Chrome version (e.g. 131)")
  .action(getAdapterBrowser);

async function getAdapterBrowser(chromeVersion: string) {
  if (!SUPPORTED_VERSIONS.includes(chromeVersion)) {
    console.error(
      `Unsupported Chrome version: ${chromeVersion}. Supported: ${SUPPORTED_VERSIONS.join(", ")}`
    );
    await exitProcess(1);
    return;
  }

  const browserPath = getBrowserPath();
  if (!existsSync(browserPath)) {
    console.error(
      `Replay browser not found at ${browserPath}. Run 'replayio update' first.`
    );
    await exitProcess(1);
    return;
  }

  const adapterMain = resolve(__dirname, "..", "..", "adapter", "main.js");
  if (!existsSync(adapterMain)) {
    console.error(`Adapter module not found at ${adapterMain}`);
    await exitProcess(1);
    return;
  }

  const outputDir = getReplayPath("adapter");
  await mkdir(outputDir, { recursive: true });

  const wrapperPath = join(outputDir, `replay-chrome-${chromeVersion}`);
  const wrapper = [
    "#!/bin/bash",
    `# Auto-generated by: replayio get-adapter-browser ${chromeVersion}`,
    `exec node "${adapterMain}" --replay-chrome-bin="${browserPath}" "$@"`,
    "",
  ].join("\n");

  await writeFile(wrapperPath, wrapper, { mode: 0o755 });
  await chmod(wrapperPath, 0o755);

  // Output just the path so callers can capture it
  console.log(wrapperPath);
  await exitProcess(0);
}
