name: Playwright tests
on:
  pull_request:
  push:
    branches: [main, playwright-next]

jobs:
  playwright-tests:
    name: Playwright tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        playwright-version: [1.52.x, next]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "yarn"
      - run: yarn --immutable
      - run: yarn run build
      # it's added here to deps to avoid affecting Turborepo's dependency graph and related caching
      - run: yarn add --dev "replayio@workspace:^"
      - run: npx --no replayio install
      # @playwright/test depends on fixed version of playwright and that depends on fixed version of playwright-core
      # so it should be enough to only enforce the version of @playwright/test here
      - run: yarn set resolution "@playwright/test@*" ${{ matrix.playwright-version }}
      - run: yarn test
        working-directory: examples/create-react-app-typescript
      - run: node test/upload-and-check-recording.js
        working-directory: examples/create-react-app-typescript
        env:
          REPLAY_API_KEY: ${{ secrets.RECORD_REPLAY_API_KEY }}
